version: '2.1'
services:

  mobile-config:
    image: registry.fit2cloud.com/innovation/mobile-config:master
    container_name: mobile-config
    volumes:
    - host-opt-fit2cloud-conf:/opt/fit2cloud/conf
    - host-opt-fit2cloud-logs:/opt/fit2cloud/logs
    mem_limit: 1024m
    depends_on:
      management-center:
        condition: service_healthy
    networks:
    - cmp-network
